name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux.zip'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip curl
     
      - name: Clone egcd521/build-afdo repo (Âê´ perf.zip)
        run: |
          git clone https://github.com/egcd521/build-afdo.git
          ls -lh build-afdo/perf.zip

      - name: Unzip perf.zip
        run: |
         unzip build-afdo/perf.zip -d build-afdo
         ls -lh build-afdo/

      - name: Download and extract create_llvm_prof binary
        run: |
          curl -LO https://github.com/google/autofdo/releases/download/v0.30.1/create_llvm_prof-x86_64-v0.30.1.zip
          unzip create_llvm_prof-x86_64-v0.30.1.zip
          chmod +x create_llvm_prof

      - name: Download and unzip vmlinux.zip
        run: |
         curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux.zip
         unzip -j vmlinux.zip vmlinux -d .
         ls -lh vmlinux

      - name: Generate kernel.afdo
        run: |
          ./create_llvm_prof --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo
